sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - EXECUTE_COVERAGE=true
    - php: 7
    - php: 7.1
  allow_failures:
    - php: hhvm
    
script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then phpunit --configuration phpunit.xml --coverage-clover clover.xml; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpunit tests; fi
  
after_success:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi
